"""empty message

Revision ID: 782dc2ef137a
Revises: 29a7b60bf842
Create Date: 2025-04-08 14:35:18.219249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782dc2ef137a'
down_revision = '29a7b60bf842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('reports_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reports_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
